# Generated by Django 2.0.2 on 2018-03-01 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('para', models.CharField(max_length=80)),
                ('cargo_para', models.CharField(max_length=80)),
                ('assunto', models.CharField(max_length=80)),
                ('texto', models.TextField()),
                ('numero', models.IntegerField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficio.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('logo', models.ImageField(upload_to='')),
                ('cnpj', models.IntegerField()),
                ('cidade', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('ramal', models.IntegerField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficio.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('endereco', models.TextField()),
                ('telefone', models.IntegerField()),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficio.Orgao')),
            ],
        ),
        migrations.AddField(
            model_name='responsavel',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficio.Setor'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficio.Orgao'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficio.Responsavel'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficio.Setor'),
        ),
    ]
