# Generated by Django 2.0.2 on 2018-03-14 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oficio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficio',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='orgao',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='setor',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='nome',
        ),
        migrations.AddField(
            model_name='responsavel',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
