# Generated by Django 2.0.2 on 2018-03-05 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='ano',
            field=models.DateField(default=datetime.datetime(2018, 3, 5, 11, 45, 41, 744189), verbose_name=datetime.datetime(2018, 3, 5, 11, 45, 41, 744184)),
        ),
    ]
