# Generated by Django 2.0.2 on 2018-03-14 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficio', '0002_auto_20180314_0918'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oficio',
            unique_together={('responsavel', 'numero')},
        ),
    ]
