# Generated by Django 2.0.2 on 2018-03-05 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficio', '0002_oficio_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='ano',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 11, 55, 11, 615846), verbose_name=datetime.datetime(2018, 3, 5, 11, 55, 11, 615841)),
        ),
    ]
