# Generated by Django 2.0.2 on 2018-03-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficio', '0003_auto_20180314_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='tratamento',
            field=models.CharField(choices=[('Senhor', 'Sr.'), ('Senhora', 'Srª'), ('Vossa Senhoria', 'V.S.ª'), ('Vossa Excelência', 'V.Ex.ª'), ('Vossa Excelência', 'V.Ex.ª')], default='Senhor', max_length=20),
        ),
    ]
