# Generated by Django 2.0.2 on 2018-03-05 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oficio', '0003_auto_20180305_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='ano',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
