# Generated by Django 2.0.2 on 2018-03-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficio', '0004_auto_20180305_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficio',
            name='ano',
        ),
    ]
