# Generated by Django 2.0.2 on 2018-03-07 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oficio', '0006_auto_20180305_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='nome',
        ),
        migrations.AddField(
            model_name='responsavel',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
