# Generated by Django 2.0.2 on 2018-03-11 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficio', '0009_auto_20180307_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='orgao',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='oficio.Orgao'),
        ),
    ]
