# Generated by Django 2.0.2 on 2018-03-11 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficio', '0010_responsavel_orgao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficio',
            name='orgao',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='orgao',
        ),
    ]
