# Generated by Django 2.0.2 on 2018-03-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficio', '0011_auto_20180311_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
