# Generated by Django 2.0.2 on 2018-03-14 01:25

from django.db import migrations, models
import oficio.models


class Migration(migrations.Migration):

    dependencies = [
        ('oficio', '0014_auto_20180313_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='numero',
            field=models.IntegerField(default=oficio.models.autoincrement),
        ),
    ]
