version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 582676da
       MYSQL_DATABASE: aplicacao
       MYSQL_USER: root
       MYSQL_PASSWORD: 582676da

   nginx:
     depends_on:
       - db
     image: nginx:latest
     ports:
       - "8080:80"
     restart: always
     environment:
       DB_HOST: db:3306
       DB_USER: root
       DB_PASSWORD: 582676da
volumes:
    db_data: